### ISSUE TITLE
Unhandled Rejection (Error): Cannot find module './dummyproject/AwarenessContent'.

### ISSUE THREAD

**Issue by nidhinmahesh** [hotosm/hot-dashboard#4]
![image](https://user-images.githubusercontent.com/20723857/54082003-c7be2b00-4334-11e9-8d7a-89e52f3dd956.png)
also in ramani huria
![image](https://user-images.githubusercontent.com/20723857/54082009-de648200-4334-11e9-852c-081e458f9ab1.png)

**Comment by VarunBhandia** [comment]
@nidhinmahesh Can I work on this issue?

**Comment by VarunBhandia** [comment]
@ramyaragupathy ma'am please review my PR #10
